### ISSUE TITLE
온보딩 관련 UI 구현

### ISSUE THREAD

**Issue by kweonsikyung** [SS507-today/project-today-flutter#16]
## 📌 어떤 EPIC/Milestone 인가요?
온보딩 UI 작업 및 (백앤드와)테스트를 위한 카카오 로그인 임시 구현

## 🗓️ Due date
~0904

## 🌈 Feature List

- [x] 온보딩 스크린 작업 ( 로그인/닉넴입력 UI )
- [ ] 카카오 sdk 추가로 관련 키 담은 env 전달 

## ✅ Check List

- [x] 담당자 등록
- [x] 라벨 등록 `EPIC`
- [x] DDL 체크
