### ISSUE TITLE
API 호출 인스턴스 구현

### ISSUE THREAD

**Issue by kweonsikyung** [SS507-today/project-today-flutter#49]
## 📌 어떤 EPIC/Milestone 인가요?
* API 호출 인스턴스 구현
* 테스트 코드 작성 /member

## 🗓️ Due date
1004

## 🌈 Feature List

- [x] API 호출 인스턴스 구현
- [x] 테스트 코드 작성 /member

## ✅ Check List

- [x] 담당자 등록
- [x] 라벨 등록 `EPIC`
- [x] DDL 체크
