### ISSUE TITLE
공유그룹 관련 API

### ISSUE THREAD

**Issue by kweonsikyung** [SS507-today/project-today-flutter#53]
## 📌 어떤 EPIC/Milestone 인가요?
swagger: /swagger-ui/index.html#/02.%20%EA%B3%B5%EC%9C%A0%EA%B7%B8%EB%A3%B9%20%EA%B4%80%EB%A0%A8%20API
figma: 교환일기 홈 / 그룹 참가 / 그룹 /  그룹 생성

## 🗓️ Due date
~1016

## 🌈 Feature List

- [x] 그룹 
    - [x] 그룹 없을 때
    - [x] 그룹 있을 때
- [x] 그룹 생성
    - [x] 그룹생성 flow -3 
- [x] 그룹 참가
    - [x] 참가 코드 검색
    - [x] 초대 수락
- [x] 교환일기 홈
    - [x] 교환일기 홈
    - [ ] 교환일기 보관함 @bakhwee-bug diaryAPI 쪽이에용
    - [x] 교환일기 설정
    - [ ] 그룹 설정    

## ✅ Check List

- [x] 담당자 등록
- [x] 라벨 등록 `EPIC`
- [x] DDL 체크
