### ISSUE TITLE
최신 번들 조회 API

### ISSUE THREAD

**Issue by bakhwee-bug** [SS507-today/project-today-flutter#79]
## 📌 어떤 EPIC/Milestone 인가요?
최신 번들 조회 API

## 🗓️ Due date
1109

## 🌈 Feature List

- [x] 최신 번들 조회 API 연결
- [x] 지난 일기장에서 제일 최근 일기 빼던 거 수정

## ✅ Check List

- [x] 담당자 등록
- [x] 라벨 등록 `EPIC`
- [x] DDL 체크
